version: '3'

services:
  mydb:
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
  mdb:
    image: postgres:9
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: mdb
    ports:
      - 5433:5432
