no-hooks=true
no-tests=true
no-auto-timestamps=true
no-context=true
blacklist=["schema_migrations"]
[psql]
  dbname="mydb"
  host="localhost"
  port=5432
  user="postgres"
  pass="12345"
  sslmode="disable"
