// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Bookmark         string
	BookmarkFolder   string
	Folder           string
	History          string
	PlaylistItems    string
	Playlists        string
	Reactions        string
	SchemaMigrations string
	Subscriptions    string
	Users            string
}{
	Bookmark:         "bookmark",
	BookmarkFolder:   "bookmark_folder",
	Folder:           "folder",
	History:          "history",
	PlaylistItems:    "playlist_items",
	Playlists:        "playlists",
	Reactions:        "reactions",
	SchemaMigrations: "schema_migrations",
	Subscriptions:    "subscriptions",
	Users:            "users",
}
