// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BookmarkFolder   string
	BookmarkTag      string
	Bookmarks        string
	Folders          string
	History          string
	PlaylistItems    string
	Playlists        string
	Reactions        string
	SchemaMigrations string
	Subscriptions    string
	Users            string
}{
	BookmarkFolder:   "bookmark_folder",
	BookmarkTag:      "bookmark_tag",
	Bookmarks:        "bookmarks",
	Folders:          "folders",
	History:          "history",
	PlaylistItems:    "playlist_items",
	Playlists:        "playlists",
	Reactions:        "reactions",
	SchemaMigrations: "schema_migrations",
	Subscriptions:    "subscriptions",
	Users:            "users",
}
