// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// BookmarkTag is an object representing the database table.
type BookmarkTag struct {
	BookmarkID int64  `boil:"bookmark_id" json:"bookmark_id" toml:"bookmark_id" yaml:"bookmark_id"`
	TagUID     string `boil:"tag_uid" json:"tag_uid" toml:"tag_uid" yaml:"tag_uid"`

	R *bookmarkTagR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L bookmarkTagL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BookmarkTagColumns = struct {
	BookmarkID string
	TagUID     string
}{
	BookmarkID: "bookmark_id",
	TagUID:     "tag_uid",
}

var BookmarkTagTableColumns = struct {
	BookmarkID string
	TagUID     string
}{
	BookmarkID: "bookmark_tag.bookmark_id",
	TagUID:     "bookmark_tag.tag_uid",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var BookmarkTagWhere = struct {
	BookmarkID whereHelperint64
	TagUID     whereHelperstring
}{
	BookmarkID: whereHelperint64{field: "\"bookmark_tag\".\"bookmark_id\""},
	TagUID:     whereHelperstring{field: "\"bookmark_tag\".\"tag_uid\""},
}

// BookmarkTagRels is where relationship names are stored.
var BookmarkTagRels = struct {
	Bookmark string
}{
	Bookmark: "Bookmark",
}

// bookmarkTagR is where relationships are stored.
type bookmarkTagR struct {
	Bookmark *Bookmark `boil:"Bookmark" json:"Bookmark" toml:"Bookmark" yaml:"Bookmark"`
}

// NewStruct creates a new relationship struct
func (*bookmarkTagR) NewStruct() *bookmarkTagR {
	return &bookmarkTagR{}
}

// bookmarkTagL is where Load methods for each relationship are stored.
type bookmarkTagL struct{}

var (
	bookmarkTagAllColumns            = []string{"bookmark_id", "tag_uid"}
	bookmarkTagColumnsWithoutDefault = []string{"bookmark_id", "tag_uid"}
	bookmarkTagColumnsWithDefault    = []string{}
	bookmarkTagPrimaryKeyColumns     = []string{"tag_uid", "bookmark_id"}
)

type (
	// BookmarkTagSlice is an alias for a slice of pointers to BookmarkTag.
	// This should almost always be used instead of []BookmarkTag.
	BookmarkTagSlice []*BookmarkTag

	bookmarkTagQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	bookmarkTagType                 = reflect.TypeOf(&BookmarkTag{})
	bookmarkTagMapping              = queries.MakeStructMapping(bookmarkTagType)
	bookmarkTagPrimaryKeyMapping, _ = queries.BindMapping(bookmarkTagType, bookmarkTagMapping, bookmarkTagPrimaryKeyColumns)
	bookmarkTagInsertCacheMut       sync.RWMutex
	bookmarkTagInsertCache          = make(map[string]insertCache)
	bookmarkTagUpdateCacheMut       sync.RWMutex
	bookmarkTagUpdateCache          = make(map[string]updateCache)
	bookmarkTagUpsertCacheMut       sync.RWMutex
	bookmarkTagUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single bookmarkTag record from the query.
func (q bookmarkTagQuery) One(exec boil.Executor) (*BookmarkTag, error) {
	o := &BookmarkTag{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for bookmark_tag")
	}

	return o, nil
}

// All returns all BookmarkTag records from the query.
func (q bookmarkTagQuery) All(exec boil.Executor) (BookmarkTagSlice, error) {
	var o []*BookmarkTag

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to BookmarkTag slice")
	}

	return o, nil
}

// Count returns the count of all BookmarkTag records in the query.
func (q bookmarkTagQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count bookmark_tag rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q bookmarkTagQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if bookmark_tag exists")
	}

	return count > 0, nil
}

// Bookmark pointed to by the foreign key.
func (o *BookmarkTag) Bookmark(mods ...qm.QueryMod) bookmarkQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.BookmarkID),
	}

	queryMods = append(queryMods, mods...)

	query := Bookmarks(queryMods...)
	queries.SetFrom(query.Query, "\"bookmarks\"")

	return query
}

// LoadBookmark allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (bookmarkTagL) LoadBookmark(e boil.Executor, singular bool, maybeBookmarkTag interface{}, mods queries.Applicator) error {
	var slice []*BookmarkTag
	var object *BookmarkTag

	if singular {
		object = maybeBookmarkTag.(*BookmarkTag)
	} else {
		slice = *maybeBookmarkTag.(*[]*BookmarkTag)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &bookmarkTagR{}
		}
		args = append(args, object.BookmarkID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &bookmarkTagR{}
			}

			for _, a := range args {
				if a == obj.BookmarkID {
					continue Outer
				}
			}

			args = append(args, obj.BookmarkID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`bookmarks`),
		qm.WhereIn(`bookmarks.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Bookmark")
	}

	var resultSlice []*Bookmark
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Bookmark")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for bookmarks")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for bookmarks")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Bookmark = foreign
		if foreign.R == nil {
			foreign.R = &bookmarkR{}
		}
		foreign.R.BookmarkTags = append(foreign.R.BookmarkTags, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.BookmarkID == foreign.ID {
				local.R.Bookmark = foreign
				if foreign.R == nil {
					foreign.R = &bookmarkR{}
				}
				foreign.R.BookmarkTags = append(foreign.R.BookmarkTags, local)
				break
			}
		}
	}

	return nil
}

// SetBookmark of the bookmarkTag to the related item.
// Sets o.R.Bookmark to related.
// Adds o to related.R.BookmarkTags.
func (o *BookmarkTag) SetBookmark(exec boil.Executor, insert bool, related *Bookmark) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"bookmark_tag\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"bookmark_id"}),
		strmangle.WhereClause("\"", "\"", 2, bookmarkTagPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.TagUID, o.BookmarkID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.BookmarkID = related.ID
	if o.R == nil {
		o.R = &bookmarkTagR{
			Bookmark: related,
		}
	} else {
		o.R.Bookmark = related
	}

	if related.R == nil {
		related.R = &bookmarkR{
			BookmarkTags: BookmarkTagSlice{o},
		}
	} else {
		related.R.BookmarkTags = append(related.R.BookmarkTags, o)
	}

	return nil
}

// BookmarkTags retrieves all the records using an executor.
func BookmarkTags(mods ...qm.QueryMod) bookmarkTagQuery {
	mods = append(mods, qm.From("\"bookmark_tag\""))
	return bookmarkTagQuery{NewQuery(mods...)}
}

// FindBookmarkTag retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBookmarkTag(exec boil.Executor, tagUID string, bookmarkID int64, selectCols ...string) (*BookmarkTag, error) {
	bookmarkTagObj := &BookmarkTag{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"bookmark_tag\" where \"tag_uid\"=$1 AND \"bookmark_id\"=$2", sel,
	)

	q := queries.Raw(query, tagUID, bookmarkID)

	err := q.Bind(nil, exec, bookmarkTagObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from bookmark_tag")
	}

	return bookmarkTagObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *BookmarkTag) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no bookmark_tag provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(bookmarkTagColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	bookmarkTagInsertCacheMut.RLock()
	cache, cached := bookmarkTagInsertCache[key]
	bookmarkTagInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			bookmarkTagAllColumns,
			bookmarkTagColumnsWithDefault,
			bookmarkTagColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(bookmarkTagType, bookmarkTagMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(bookmarkTagType, bookmarkTagMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"bookmark_tag\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"bookmark_tag\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into bookmark_tag")
	}

	if !cached {
		bookmarkTagInsertCacheMut.Lock()
		bookmarkTagInsertCache[key] = cache
		bookmarkTagInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the BookmarkTag.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *BookmarkTag) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	bookmarkTagUpdateCacheMut.RLock()
	cache, cached := bookmarkTagUpdateCache[key]
	bookmarkTagUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			bookmarkTagAllColumns,
			bookmarkTagPrimaryKeyColumns,
		)

		if len(wl) == 0 {
			return 0, errors.New("models: unable to update bookmark_tag, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"bookmark_tag\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, bookmarkTagPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(bookmarkTagType, bookmarkTagMapping, append(wl, bookmarkTagPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update bookmark_tag row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for bookmark_tag")
	}

	if !cached {
		bookmarkTagUpdateCacheMut.Lock()
		bookmarkTagUpdateCache[key] = cache
		bookmarkTagUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q bookmarkTagQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for bookmark_tag")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for bookmark_tag")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BookmarkTagSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bookmarkTagPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"bookmark_tag\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, bookmarkTagPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in bookmarkTag slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all bookmarkTag")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *BookmarkTag) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no bookmark_tag provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(bookmarkTagColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	bookmarkTagUpsertCacheMut.RLock()
	cache, cached := bookmarkTagUpsertCache[key]
	bookmarkTagUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			bookmarkTagAllColumns,
			bookmarkTagColumnsWithDefault,
			bookmarkTagColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			bookmarkTagAllColumns,
			bookmarkTagPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert bookmark_tag, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(bookmarkTagPrimaryKeyColumns))
			copy(conflict, bookmarkTagPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"bookmark_tag\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(bookmarkTagType, bookmarkTagMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(bookmarkTagType, bookmarkTagMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert bookmark_tag")
	}

	if !cached {
		bookmarkTagUpsertCacheMut.Lock()
		bookmarkTagUpsertCache[key] = cache
		bookmarkTagUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single BookmarkTag record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *BookmarkTag) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no BookmarkTag provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), bookmarkTagPrimaryKeyMapping)
	sql := "DELETE FROM \"bookmark_tag\" WHERE \"tag_uid\"=$1 AND \"bookmark_id\"=$2"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from bookmark_tag")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for bookmark_tag")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q bookmarkTagQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no bookmarkTagQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from bookmark_tag")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for bookmark_tag")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BookmarkTagSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bookmarkTagPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"bookmark_tag\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, bookmarkTagPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from bookmarkTag slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for bookmark_tag")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *BookmarkTag) Reload(exec boil.Executor) error {
	ret, err := FindBookmarkTag(exec, o.TagUID, o.BookmarkID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BookmarkTagSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BookmarkTagSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bookmarkTagPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"bookmark_tag\".* FROM \"bookmark_tag\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, bookmarkTagPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BookmarkTagSlice")
	}

	*o = slice

	return nil
}

// BookmarkTagExists checks if the BookmarkTag row exists.
func BookmarkTagExists(exec boil.Executor, tagUID string, bookmarkID int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"bookmark_tag\" where \"tag_uid\"=$1 AND \"bookmark_id\"=$2 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, tagUID, bookmarkID)
	}
	row := exec.QueryRow(sql, tagUID, bookmarkID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if bookmark_tag exists")
	}

	return exists, nil
}
