// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Playlist is an object representing the database table.
type Playlist struct {
	ID            int64       `boil:"id" json:"id" toml:"id" yaml:"id"`
	UID           string      `boil:"uid" json:"uid" toml:"uid" yaml:"uid"`
	UserID        int64       `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Name          null.String `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`
	Public        bool        `boil:"public" json:"public" toml:"public" yaml:"public"`
	Properties    null.JSON   `boil:"properties" json:"properties,omitempty" toml:"properties" yaml:"properties,omitempty"`
	CreatedAt     time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	PosterUnitUID null.String `boil:"poster_unit_uid" json:"poster_unit_uid,omitempty" toml:"poster_unit_uid" yaml:"poster_unit_uid,omitempty"`

	R *playlistR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L playlistL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PlaylistColumns = struct {
	ID            string
	UID           string
	UserID        string
	Name          string
	Public        string
	Properties    string
	CreatedAt     string
	PosterUnitUID string
}{
	ID:            "id",
	UID:           "uid",
	UserID:        "user_id",
	Name:          "name",
	Public:        "public",
	Properties:    "properties",
	CreatedAt:     "created_at",
	PosterUnitUID: "poster_unit_uid",
}

var PlaylistTableColumns = struct {
	ID            string
	UID           string
	UserID        string
	Name          string
	Public        string
	Properties    string
	CreatedAt     string
	PosterUnitUID string
}{
	ID:            "playlists.id",
	UID:           "playlists.uid",
	UserID:        "playlists.user_id",
	Name:          "playlists.name",
	Public:        "playlists.public",
	Properties:    "playlists.properties",
	CreatedAt:     "playlists.created_at",
	PosterUnitUID: "playlists.poster_unit_uid",
}

// Generated where

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

var PlaylistWhere = struct {
	ID            whereHelperint64
	UID           whereHelperstring
	UserID        whereHelperint64
	Name          whereHelpernull_String
	Public        whereHelperbool
	Properties    whereHelpernull_JSON
	CreatedAt     whereHelpertime_Time
	PosterUnitUID whereHelpernull_String
}{
	ID:            whereHelperint64{field: "\"playlists\".\"id\""},
	UID:           whereHelperstring{field: "\"playlists\".\"uid\""},
	UserID:        whereHelperint64{field: "\"playlists\".\"user_id\""},
	Name:          whereHelpernull_String{field: "\"playlists\".\"name\""},
	Public:        whereHelperbool{field: "\"playlists\".\"public\""},
	Properties:    whereHelpernull_JSON{field: "\"playlists\".\"properties\""},
	CreatedAt:     whereHelpertime_Time{field: "\"playlists\".\"created_at\""},
	PosterUnitUID: whereHelpernull_String{field: "\"playlists\".\"poster_unit_uid\""},
}

// PlaylistRels is where relationship names are stored.
var PlaylistRels = struct {
	User          string
	PlaylistItems string
}{
	User:          "User",
	PlaylistItems: "PlaylistItems",
}

// playlistR is where relationships are stored.
type playlistR struct {
	User          *User             `boil:"User" json:"User" toml:"User" yaml:"User"`
	PlaylistItems PlaylistItemSlice `boil:"PlaylistItems" json:"PlaylistItems" toml:"PlaylistItems" yaml:"PlaylistItems"`
}

// NewStruct creates a new relationship struct
func (*playlistR) NewStruct() *playlistR {
	return &playlistR{}
}

// playlistL is where Load methods for each relationship are stored.
type playlistL struct{}

var (
	playlistAllColumns            = []string{"id", "uid", "user_id", "name", "public", "properties", "created_at", "poster_unit_uid"}
	playlistColumnsWithoutDefault = []string{"uid", "user_id"}
	playlistColumnsWithDefault    = []string{"id", "name", "public", "properties", "created_at", "poster_unit_uid"}
	playlistPrimaryKeyColumns     = []string{"id"}
	playlistGeneratedColumns      = []string{}
)

type (
	// PlaylistSlice is an alias for a slice of pointers to Playlist.
	// This should almost always be used instead of []Playlist.
	PlaylistSlice []*Playlist

	playlistQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	playlistType                 = reflect.TypeOf(&Playlist{})
	playlistMapping              = queries.MakeStructMapping(playlistType)
	playlistPrimaryKeyMapping, _ = queries.BindMapping(playlistType, playlistMapping, playlistPrimaryKeyColumns)
	playlistInsertCacheMut       sync.RWMutex
	playlistInsertCache          = make(map[string]insertCache)
	playlistUpdateCacheMut       sync.RWMutex
	playlistUpdateCache          = make(map[string]updateCache)
	playlistUpsertCacheMut       sync.RWMutex
	playlistUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single playlist record from the query.
func (q playlistQuery) One(exec boil.Executor) (*Playlist, error) {
	o := &Playlist{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for playlists")
	}

	return o, nil
}

// All returns all Playlist records from the query.
func (q playlistQuery) All(exec boil.Executor) (PlaylistSlice, error) {
	var o []*Playlist

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Playlist slice")
	}

	return o, nil
}

// Count returns the count of all Playlist records in the query.
func (q playlistQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count playlists rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q playlistQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if playlists exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *Playlist) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	query := Users(queryMods...)
	queries.SetFrom(query.Query, "\"users\"")

	return query
}

// PlaylistItems retrieves all the playlist_item's PlaylistItems with an executor.
func (o *Playlist) PlaylistItems(mods ...qm.QueryMod) playlistItemQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"playlist_items\".\"playlist_id\"=?", o.ID),
	)

	query := PlaylistItems(queryMods...)
	queries.SetFrom(query.Query, "\"playlist_items\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"playlist_items\".*"})
	}

	return query
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (playlistL) LoadUser(e boil.Executor, singular bool, maybePlaylist interface{}, mods queries.Applicator) error {
	var slice []*Playlist
	var object *Playlist

	if singular {
		object = maybePlaylist.(*Playlist)
	} else {
		slice = *maybePlaylist.(*[]*Playlist)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &playlistR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &playlistR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.Playlists = append(foreign.R.Playlists, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.Playlists = append(foreign.R.Playlists, local)
				break
			}
		}
	}

	return nil
}

// LoadPlaylistItems allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (playlistL) LoadPlaylistItems(e boil.Executor, singular bool, maybePlaylist interface{}, mods queries.Applicator) error {
	var slice []*Playlist
	var object *Playlist

	if singular {
		object = maybePlaylist.(*Playlist)
	} else {
		slice = *maybePlaylist.(*[]*Playlist)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &playlistR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &playlistR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`playlist_items`),
		qm.WhereIn(`playlist_items.playlist_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load playlist_items")
	}

	var resultSlice []*PlaylistItem
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice playlist_items")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on playlist_items")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for playlist_items")
	}

	if singular {
		object.R.PlaylistItems = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &playlistItemR{}
			}
			foreign.R.Playlist = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.PlaylistID {
				local.R.PlaylistItems = append(local.R.PlaylistItems, foreign)
				if foreign.R == nil {
					foreign.R = &playlistItemR{}
				}
				foreign.R.Playlist = local
				break
			}
		}
	}

	return nil
}

// SetUser of the playlist to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Playlists.
func (o *Playlist) SetUser(exec boil.Executor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"playlists\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, playlistPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &playlistR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			Playlists: PlaylistSlice{o},
		}
	} else {
		related.R.Playlists = append(related.R.Playlists, o)
	}

	return nil
}

// AddPlaylistItems adds the given related objects to the existing relationships
// of the playlist, optionally inserting them as new records.
// Appends related to o.R.PlaylistItems.
// Sets related.R.Playlist appropriately.
func (o *Playlist) AddPlaylistItems(exec boil.Executor, insert bool, related ...*PlaylistItem) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.PlaylistID = o.ID
			if err = rel.Insert(exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"playlist_items\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"playlist_id"}),
				strmangle.WhereClause("\"", "\"", 2, playlistItemPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}
			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.PlaylistID = o.ID
		}
	}

	if o.R == nil {
		o.R = &playlistR{
			PlaylistItems: related,
		}
	} else {
		o.R.PlaylistItems = append(o.R.PlaylistItems, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &playlistItemR{
				Playlist: o,
			}
		} else {
			rel.R.Playlist = o
		}
	}
	return nil
}

// Playlists retrieves all the records using an executor.
func Playlists(mods ...qm.QueryMod) playlistQuery {
	mods = append(mods, qm.From("\"playlists\""))
	return playlistQuery{NewQuery(mods...)}
}

// FindPlaylist retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPlaylist(exec boil.Executor, iD int64, selectCols ...string) (*Playlist, error) {
	playlistObj := &Playlist{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"playlists\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, playlistObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from playlists")
	}

	return playlistObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Playlist) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no playlists provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(playlistColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	playlistInsertCacheMut.RLock()
	cache, cached := playlistInsertCache[key]
	playlistInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			playlistAllColumns,
			playlistColumnsWithDefault,
			playlistColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(playlistType, playlistMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(playlistType, playlistMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"playlists\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"playlists\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into playlists")
	}

	if !cached {
		playlistInsertCacheMut.Lock()
		playlistInsertCache[key] = cache
		playlistInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Playlist.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Playlist) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	playlistUpdateCacheMut.RLock()
	cache, cached := playlistUpdateCache[key]
	playlistUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			playlistAllColumns,
			playlistPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update playlists, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"playlists\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, playlistPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(playlistType, playlistMapping, append(wl, playlistPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update playlists row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for playlists")
	}

	if !cached {
		playlistUpdateCacheMut.Lock()
		playlistUpdateCache[key] = cache
		playlistUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q playlistQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for playlists")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for playlists")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PlaylistSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), playlistPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"playlists\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, playlistPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in playlist slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all playlist")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Playlist) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no playlists provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(playlistColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	playlistUpsertCacheMut.RLock()
	cache, cached := playlistUpsertCache[key]
	playlistUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			playlistAllColumns,
			playlistColumnsWithDefault,
			playlistColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			playlistAllColumns,
			playlistPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert playlists, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(playlistPrimaryKeyColumns))
			copy(conflict, playlistPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"playlists\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(playlistType, playlistMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(playlistType, playlistMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert playlists")
	}

	if !cached {
		playlistUpsertCacheMut.Lock()
		playlistUpsertCache[key] = cache
		playlistUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Playlist record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Playlist) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Playlist provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), playlistPrimaryKeyMapping)
	sql := "DELETE FROM \"playlists\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from playlists")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for playlists")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q playlistQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no playlistQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from playlists")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for playlists")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PlaylistSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), playlistPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"playlists\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, playlistPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from playlist slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for playlists")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Playlist) Reload(exec boil.Executor) error {
	ret, err := FindPlaylist(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PlaylistSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PlaylistSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), playlistPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"playlists\".* FROM \"playlists\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, playlistPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PlaylistSlice")
	}

	*o = slice

	return nil
}

// PlaylistExists checks if the Playlist row exists.
func PlaylistExists(exec boil.Executor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"playlists\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if playlists exists")
	}

	return exists, nil
}
