package consts

const (
	// Collection Types
	CT_ARTICLES           = "ARTICLES"
	CT_BOOKS              = "BOOKS"
	CT_CHILDREN_LESSONS   = "CHILDREN_LESSONS"
	CT_CLIPS              = "CLIPS"
	CT_CONGRESS           = "CONGRESS"
	CT_DAILY_LESSON       = "DAILY_LESSON"
	CT_FRIENDS_GATHERINGS = "FRIENDS_GATHERINGS"
	CT_HOLIDAY            = "HOLIDAY"
	CT_LECTURE_SERIES     = "LECTURE_SERIES"
	CT_LESSONS_SERIES     = "LESSONS_SERIES"
	CT_MEALS              = "MEALS"
	CT_PICNIC             = "PICNIC"
	CT_SONGS              = "SONGS"
	CT_SPECIAL_LESSON     = "SPECIAL_LESSON"
	CT_UNITY_DAY          = "UNITY_DAY"
	CT_VIDEO_PROGRAM      = "VIDEO_PROGRAM"
	CT_VIRTUAL_LESSONS    = "VIRTUAL_LESSONS"
	CT_WOMEN_LESSONS      = "WOMEN_LESSONS"
)
