name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mydb:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydb
        options: >-
          --health-cmd="pg_isready" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

      mdb:
        image: postgres:14
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mdb
        options: >-
          --health-cmd="pg_isready" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.17

      - name: Run unit tests
        env:
          GOOS: linux
          CGO_ENABLED: 0
          MYDB_URL: postgres://user:password@localhost/mydb?sslmode=disable
          MDB_URL: postgres://user:password@localhost:5433/mdb?sslmode=disable
        run: |
          set -o pipefail
          go test -v $(go list ./... | grep -v /models) | tee test.log
        continue-on-error: false

      - name: Upload test log if tests fail
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test.log

  build:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ success() || needs.test.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.BBDEPLOYMENT_DOCKERHUB_USERNAME }}
          password: ${{ secrets.BBDEPLOYMENT_DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            bneibaruch/archive_my:latest
            bneibaruch/archive_my:gh_${{github.run_number}}
          build-args: |
            build_number=gh_${{github.run_number}}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Set deployment variables
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
            echo "SSH_HOST=${{ secrets.ARCHIVE_HOST_STAGING }}" >> $GITHUB_ENV
          else
            echo "SSH_HOST=${{ secrets.ARCHIVE_HOST_PRODUCTION }}" >> $GITHUB_ENV
          fi
            
      - name: Deploy to ${{ github.event.inputs.environment }} via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SSH_HOST }}
          username: root
          key: ${{ secrets.BBDEPLOYMENT_SSH_PRIVATE_KEY }}
          proxy_host: ${{ secrets.SSH_PROXY_HOST }}
          proxy_username: ${{ secrets.SSH_PROXY_USERNAME }}
          proxy_key: ${{ secrets.BBDEPLOYMENT_SSH_PRIVATE_KEY }}
          script: |
            cd /root/archive-docker
            sed -i 's/ARCHIVE_MY_VERSION.*/ARCHIVE_MY_VERSION=gh_${{github.run_number}}/g' .env
            docker compose -f docker-compose.yml -f docker-compose-my.yml pull archive_my
            host/migrations_archive_my.sh
            docker compose -f docker-compose.yml -f docker-compose-my.yml up -d --no-deps archive_my

