// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	History          string
	Likes            string
	Playlist         string
	PlaylistItem     string
	SchemaMigrations string
	Subscriptions    string
}{
	History:          "history",
	Likes:            "likes",
	Playlist:         "playlist",
	PlaylistItem:     "playlist_item",
	SchemaMigrations: "schema_migrations",
	Subscriptions:    "subscriptions",
}
